import { Shipment } from "@/lib/types/shipment";

export const mockShipmentsList: Shipment[] = [
  {
    id: "SHP-8472",
    shipmentNumber: "SHP-8472",
    status: "Delivered",
    clientId: "CL-1001",
    clientName: "Global Logistics Inc.",
    importer: "Global Logistics Inc.",
    exporter: "Shanghai Trading Co.",
    consignee: "Global Logistics Inc.",
    containerNumber: "MSKU4920193",
    containerSize: "40ft",
    containerType: "High Cube",
    shippingLine: "Maersk",
    vesselName: "Emma Maersk",
    voyageNumber: "192A",
    originCountry: "China",
    destinationCountry: "USA",
    loadingPort: "Shanghai, CN",
    dischargePort: "Los Angeles, US",
    arrivalPort: "Los Angeles, US",
    departureDate: "2026-05-01",
    eta: "2026-05-15",
    etd: "2026-05-01",
    incoterms: "FOB",
    transportType: "Sea",
    products: [
      { id: "P-1", name: "Electronics", hsCode: "8517.12.00", quantity: 1000, weight: 500 },
      { id: "P-2", name: "Accessories", hsCode: "8529.90.00", quantity: 500, weight: 200 }
    ],
    hsCodes: ["8517.12.00", "8529.90.00"],
    grossWeight: 750,
    netWeight: 700,
    packageCount: 1500,
    packageType: "Pallets",
    description: "Consumer electronics and accessories",
    boeId: "BOE-99231",
    boeNumber: "BOE-99231",
    dutyAmount: 24500,
    customsStatus: "Cleared",
    clearanceStatus: "Approved",
    assignedEmployeeId: "EMP-001",
    assignedEmployeeName: "Alex Mercer",
    createdAt: "2026-04-20T10:00:00Z",
    updatedAt: "2026-05-16T14:30:00Z",
    timeline: [
      { id: "T-1", status: "Booked", date: "2026-04-20", time: "10:00 AM", location: "Shanghai", responsibleEmployee: "Alex Mercer", notes: "Booking confirmed with Maersk" },
      { id: "T-2", status: "Loaded", date: "2026-04-28", time: "02:00 PM", location: "Shanghai Port", responsibleEmployee: "Alex Mercer", notes: "Container loaded on vessel" },
      { id: "T-3", status: "In Transit", date: "2026-05-01", time: "08:00 AM", location: "Pacific Ocean", responsibleEmployee: "Alex Mercer", notes: "Vessel departed" },
      { id: "T-4", status: "Arrived", date: "2026-05-15", time: "11:00 AM", location: "Los Angeles Port", responsibleEmployee: "Alex Mercer", notes: "Vessel arrived at destination" },
      { id: "T-5", status: "Customs Clearance", date: "2026-05-15", time: "01:00 PM", location: "Los Angeles Port", responsibleEmployee: "Sarah Jenkins", notes: "BOE submitted" },
      { id: "T-6", status: "Released", date: "2026-05-16", time: "09:00 AM", location: "Los Angeles Port", responsibleEmployee: "Sarah Jenkins", notes: "Customs cleared" },
      { id: "T-7", status: "Delivered", date: "2026-05-16", time: "02:30 PM", location: "Seattle, WA", responsibleEmployee: "Alex Mercer", notes: "Delivered to warehouse" },
    ]
  },
  {
    id: "SHP-8473",
    shipmentNumber: "SHP-8473",
    status: "In Transit",
    clientId: "CL-1002",
    clientName: "Pacific Traders LLC",
    importer: "Pacific Traders LLC",
    exporter: "Shenzhen Manufacturing",
    consignee: "Pacific Traders LLC",
    containerNumber: "CMAU1234567",
    containerSize: "20ft",
    containerType: "Standard",
    shippingLine: "CMA CGM",
    vesselName: "CMA CGM Jacques Saade",
    voyageNumber: "882B",
    originCountry: "China",
    destinationCountry: "USA",
    loadingPort: "Shenzhen, CN",
    dischargePort: "Long Beach, US",
    arrivalPort: "Long Beach, US",
    departureDate: "2026-06-20",
    eta: "2026-07-05",
    etd: "2026-06-20",
    incoterms: "CIF",
    transportType: "Sea",
    products: [
      { id: "P-3", name: "Textiles", hsCode: "6109.10.00", quantity: 5000, weight: 2000 },
    ],
    hsCodes: ["6109.10.00"],
    grossWeight: 2100,
    netWeight: 2000,
    packageCount: 200,
    packageType: "Cartons",
    description: "Cotton T-shirts",
    boeId: "BOE-99232", // Assuming it will exist
    boeNumber: "BOE-99232",
    dutyAmount: 5200,
    customsStatus: "Pending",
    clearanceStatus: "Pending",
    assignedEmployeeId: "EMP-002",
    assignedEmployeeName: "Sarah Jenkins",
    createdAt: "2026-06-15T09:00:00Z",
    updatedAt: "2026-06-25T11:00:00Z",
    timeline: [
      { id: "T-8", status: "Booked", date: "2026-06-15", time: "09:00 AM", location: "Shenzhen", responsibleEmployee: "Sarah Jenkins", notes: "Booking confirmed" },
      { id: "T-9", status: "Loaded", date: "2026-06-19", time: "04:00 PM", location: "Shenzhen Port", responsibleEmployee: "Sarah Jenkins", notes: "Container loaded" },
      { id: "T-10", status: "In Transit", date: "2026-06-20", time: "10:00 AM", location: "Pacific Ocean", responsibleEmployee: "Sarah Jenkins", notes: "Vessel departed" },
    ]
  },
  {
    id: "SHP-8474",
    shipmentNumber: "SHP-8474",
    status: "Customs Clearance",
    clientId: "CL-1003",
    clientName: "EuroImports Ltd",
    importer: "EuroImports Ltd",
    exporter: "Hamburg Exporters",
    consignee: "EuroImports Ltd",
    containerNumber: "HLCU7654321",
    containerSize: "40ft",
    containerType: "Reefer",
    shippingLine: "Hapag-Lloyd",
    vesselName: "Berlin Express",
    voyageNumber: "441C",
    originCountry: "Germany",
    destinationCountry: "USA",
    loadingPort: "Hamburg, DE",
    dischargePort: "New York, US",
    arrivalPort: "New York, US",
    departureDate: "2026-06-10",
    eta: "2026-06-28",
    etd: "2026-06-10",
    incoterms: "DDP",
    transportType: "Sea",
    products: [
      { id: "P-4", name: "Automotive Parts", hsCode: "8708.99.81", quantity: 200, weight: 1500 },
    ],
    hsCodes: ["8708.99.81"],
    grossWeight: 1600,
    netWeight: 1500,
    packageCount: 50,
    packageType: "Wooden Crates",
    description: "Precision automotive parts",
    boeId: "BOE-99233",
    boeNumber: "BOE-99233",
    dutyAmount: 8400,
    customsStatus: "Under Review",
    clearanceStatus: "Pending",
    assignedEmployeeId: "EMP-003",
    assignedEmployeeName: "David Chen",
    createdAt: "2026-06-05T10:00:00Z",
    updatedAt: "2026-06-29T10:00:00Z",
    timeline: [
      { id: "T-11", status: "Booked", date: "2026-06-05", time: "10:00 AM", location: "Hamburg", responsibleEmployee: "David Chen", notes: "Booking confirmed" },
      { id: "T-12", status: "Loaded", date: "2026-06-09", time: "01:00 PM", location: "Hamburg Port", responsibleEmployee: "David Chen", notes: "Container loaded" },
      { id: "T-13", status: "In Transit", date: "2026-06-10", time: "07:00 AM", location: "Atlantic Ocean", responsibleEmployee: "David Chen", notes: "Vessel departed" },
      { id: "T-14", status: "Arrived", date: "2026-06-28", time: "08:00 AM", location: "New York Port", responsibleEmployee: "David Chen", notes: "Vessel arrived" },
      { id: "T-15", status: "Customs Clearance", date: "2026-06-29", time: "09:00 AM", location: "New York Port", responsibleEmployee: "David Chen", notes: "Under customs review" },
    ]
  },
  {
    id: "SHP-8475",
    shipmentNumber: "SHP-8475",
    status: "Pending",
    clientId: "CL-1004",
    clientName: "Desert Traders",
    importer: "Desert Traders",
    exporter: "Dubai Exports",
    consignee: "Desert Traders",
    containerNumber: "",
    containerSize: "20ft",
    containerType: "Standard",
    shippingLine: "MSC",
    vesselName: "MSC Oscar",
    voyageNumber: "221X",
    originCountry: "UAE",
    destinationCountry: "USA",
    loadingPort: "Dubai, AE",
    dischargePort: "Miami, US",
    arrivalPort: "Miami, US",
    departureDate: "2026-07-15",
    eta: "2026-08-10",
    etd: "2026-07-15",
    incoterms: "FOB",
    transportType: "Sea",
    products: [
      { id: "P-5", name: "Dates", hsCode: "0804.10.00", quantity: 10000, weight: 5000 },
    ],
    hsCodes: ["0804.10.00"],
    grossWeight: 5200,
    netWeight: 5000,
    packageCount: 500,
    packageType: "Boxes",
    description: "Premium dates",
    boeId: "",
    boeNumber: "",
    dutyAmount: 0,
    customsStatus: "Not Started",
    clearanceStatus: "Not Started",
    assignedEmployeeId: "EMP-001",
    assignedEmployeeName: "Alex Mercer",
    createdAt: "2026-06-30T10:00:00Z",
    updatedAt: "2026-06-30T10:00:00Z",
    timeline: [
      { id: "T-16", status: "Booked", date: "2026-06-30", time: "10:00 AM", location: "Dubai", responsibleEmployee: "Alex Mercer", notes: "Booking confirmed" },
    ]
  },
  {
    id: "SHP-8476",
    shipmentNumber: "SHP-8476",
    status: "Delayed",
    clientId: "CL-1005",
    clientName: "TechCorp Industries",
    importer: "TechCorp Industries",
    exporter: "Taiwan Semiconductors",
    consignee: "TechCorp Industries",
    containerNumber: "EMCU8877665",
    containerSize: "LCL",
    containerType: "Air Cargo",
    shippingLine: "FedEx",
    vesselName: "FDX 101",
    voyageNumber: "F101",
    originCountry: "Taiwan",
    destinationCountry: "USA",
    loadingPort: "Taipei, TW",
    dischargePort: "San Francisco, US",
    arrivalPort: "San Francisco, US",
    departureDate: "2026-06-25",
    eta: "2026-06-27",
    etd: "2026-06-25",
    incoterms: "EXW",
    transportType: "Air",
    products: [
      { id: "P-6", name: "Microchips", hsCode: "8542.31.00", quantity: 50000, weight: 100 },
    ],
    hsCodes: ["8542.31.00"],
    grossWeight: 120,
    netWeight: 100,
    packageCount: 10,
    packageType: "Secure Boxes",
    description: "High-value microchips",
    boeId: "BOE-99235",
    boeNumber: "BOE-99235",
    dutyAmount: 12000,
    customsStatus: "Pending",
    clearanceStatus: "Pending",
    assignedEmployeeId: "EMP-004",
    assignedEmployeeName: "Emily Wong",
    createdAt: "2026-06-20T10:00:00Z",
    updatedAt: "2026-06-26T14:00:00Z",
    timeline: [
      { id: "T-17", status: "Booked", date: "2026-06-20", time: "10:00 AM", location: "Taipei", responsibleEmployee: "Emily Wong", notes: "Air freight booked" },
      { id: "T-18", status: "Picked Up", date: "2026-06-24", time: "09:00 AM", location: "Supplier Factory", responsibleEmployee: "Emily Wong", notes: "Cargo picked up" },
      { id: "T-19", status: "In Transit", date: "2026-06-25", time: "08:00 AM", location: "Taipei Airport", responsibleEmployee: "Emily Wong", notes: "Flight departed" },
    ]
  }
];
